version: '3'

services:
  users:
    image: users:latest
    build: ./users
    volumes:
      - ./users:/app
    expose:
      - 8200
    ports:
      - 8200:80
    container_name: users
    environment:
      - TEAM_NAME=CC_0072_0206_0262_0704
networks:
  default:
    external:
      name: dbaas-net