version: '3'

services:
  rides:
    image: rides:latest
    build: ./rides
    volumes:
      - ./rides:/app
    expose:
      - 8201
    ports:
      - 8201:80
    container_name: rides
    environment:
      - TEAM_NAME=CC_0072_0206_0262_0704
networks:
  default:
    external:
      name: dbaas-net
